redis:
  host: 0.0.0.0
  port: 6379
  timeout: 15000ms

rate-limiter:
  enabled: true
  failure-mode: FAIL_OPEN
  algorithm: leaking-bucket

  endpoints:
    - method: POST
      path: /users

      primary:
        capacity: 100
        refill-rate: 10

    - method: GET
      path: /users

      primary:
        capacity: 500
        refill-rate: 50

      secondary:
        source: HEADER
        key: uuid
        capacity: 20
        refill-rate: 2
