redis:
  host: 0.0.0.0
  port: 6379
  timeout: 2000ms
  jedis:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0

rate-limiter:
  enabled: true
  failure-mode: FAIL_OPEN

  strategies:
    ip:
      enabled: true
      capacity: 50
      refill-rate: 5

    api:
      enabled: true
      capacity: 200
      refill-rate: 20

    api-key:
      enabled: true
      capacity: 1000
      refill-rate: 100
