redis:
  host: 0.0.0.0
  port: 6379
  timeout: 15000ms
  jedis:
    pool:
      max-active: 16
      max-idle: 16
      min-idle: 2

rate-limiter:
  enabled: true
  failure-mode: FAIL_OPEN

  strategies:
    ip:
      enabled: false
      capacity: 50
      refill-rate: 5

    api:
      enabled: true
      capacity: 1000
      refill-rate: 300

    api-key:
      enabled: false
      capacity: 1000
      refill-rate: 100
